version: "2.1"
services:
    transmission:
        image: lscr.io/linuxserver/transmission:latest
        container_name: transmission
        user: 1000
        environment:
            - TZ=Europe/Brussels
            - PUID=1000
            - PGID=1000
        volumes:
            - /home/homer/configs/transmission:/config
            - /mnt/transmission/downloads:/downloads
            - /mnt/transmission/watch:/watch
        ports:
            - 9300:9091
            - 51413:51413
            - 51413:51413/udp
        restart: unless-stopped
