version: "2.1"
services:
    emby:
        image: docker.io/emby/embyserver:latest
        container_name: emby
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Brussels
        volumes:
            - /home/homer/config/emby:/config
            - /mnt/emby/series:/data/tvshows
            - /mnt/emby/movies:/data/movies
            - /mnt/emby/documentaries:/data/documentaries
        ports:
            - 8096:8096
        # devices:
        #     - /dev/vchiq:/dev/vchiq #optional
        restart: unless-stopped
