version: "1.0"
services:
    grafana:
        container_name: grafana
        image: docker.io/grafana/grafana:latest
        ports:
            - "3000:3000"
        volumes:
            - grafana_data:/var/lib/grafana
        restart: unless-stopped
