version: "3"
services:
    portainer:
        image: docker.io/portainer/portainer-ce:latest
        container_name: portainer
        ports:
            - 9443:9443
        volumes:
            - /var/portainer:/data
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped

volumes:
    data:
