#!/usr/bin/env bash

set -o errexit # Abort on nonzero exit code.
set -o nounset # Abort on unbound variable.
set -o pipefail # Don't hide errors within pipes.
# set -o xtrace   # Enable for debugging.

. /etc/os-release

lanIP() {
   printf '%s' "$(/sbin/ifconfig 2>/dev/null | grep 'inet '|grep -v '127.0.0.1'| awk '{print $2}'|cut -d':' -f2|head -1)"
}

printf '=================================================================
%4sWelcome to %s
-----------------------------------------------------------------
%4sUser: %1s
%4sOS:   %10s
%4sIP:   %10s
%4sDate: %10s
=================================================================\n' \
   '' "${HOSTNAME}" \
   '' "${USER}" \
   '' "${PRETTY_NAME}" \
   '' "$(lanIP)" \
   '' "$(date +"%A, %d %B %Y, %T")"
