#!/usr/bin/env bash

. /etc/os-release

lanIP() {
   printf '%s' "$(/sbin/ifconfig 2>/dev/null | grep 'inet '|grep -v '127.0.0.1'| awk '{print $2}'|cut -d':' -f2|head -1)"
}

printf '+----------------------------------------------------+
|                                                    |
|%4sWelcome to %s  %27s
|                                                    |
+----------------------------------------------------+
|                                                    |
|%4sUser: %1s   %35s
|%4sOS:   %10s  %4s
|%4sIP:   %10s  %29s
|%4sDate: %10s  %11s
|                                                    |
+----------------------------------------------------+\n' \
   '' "${HOSTNAME}" '|' \
   '' "${USER}" '|' \
   '' "${PRETTY_NAME}" '|' \
   '' "$(lanIP)" '|' \
   '' "$(date +"%A, %d %B %Y, %T")" '|'
