version: "3"
services:
    wireguard:
        container_name: wireguard
        image: docker.io/linuxserver/wireguard
        user: 1000
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - SERVERPORT=51820
            - PEERS=phone,laptop
            - PEERDNS=1.1.1.1,1.0.0.1
            - INTERNAL_SUBNET=10.13.13.0
            - ALLOWEDIPS=0.0.0.0/0
        ports:
            - 51820:51820/udp
        volumes:
            - /home/marge/configs/wireguard:/config
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
