name: Shellcheck

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Run shellcheck.
              run: |
                  shopt -s nullglob
                  shellcheck rockpi-sata/build.sh
                  shellcheck provisioning/homer/init.sh --exclude=SC1091
