name: Shellcheck

on:
    push:
        paths:
            - "rockpi-sata/**"
            - "provisioning/**"
    pull_request:
        paths:
            - "rockpi-sata/**"
            - "provisioning/**"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Run shellcheck on init scripts.
              run: |
                  shopt -s nullglob
                  shellcheck provisioning/init.sh --exclude=SC1091,SC1090
                  shellcheck provisioning/homer.sh --exclude=SC1091
                  shellcheck provisioning/marge.sh --exclude=SC1091
            - name: Run shellcheck on RockPi SATA install script.
              run: |
                  shopt -s nullglob
                  shellcheck rockpi-sata/install.sh --exclude=SC1091
